{\rtf1\ansi\ansicpg1252\cocoartf2822
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 ArialMT;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs26\fsmilli13333 \cf0 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 CREATE OR REPLACE DYNAMIC TABLE \{\{CONF\}\}.OUTREACH_V2.OPPORTUNITY\
TARGET_LAG = DOWNSTREAM\
WAREHOUSE = SF_TRANSFORM_WH\
REFRESH_MODE = INCREMENTAL\
INITIALIZE = ON_SCHEDULE\
DATA_METRIC_SCHEDULE = TRIGGER_ON_CHANGES\
as\
SELECT\
"ACCOUNT_ID" AS ACCOUNT_ID,\
"AMOUNT" AS AMOUNT,\
"CLOSE_DATE" AS CLOSE_DATE,\
"COMPUTED_CREATED_AT" AS COMPUTED_CREATED_AT,\
"COMPUTED_CREATOR_ID" AS COMPUTED_CREATOR_ID,\
"COMPUTED_CREATOR_TYPE" AS COMPUTED_CREATOR_TYPE,\
"CREATED_AT" AS CREATED_AT,\
"CREATOR_ID" AS CREATOR_ID,\
"CREATOR_TYPE" AS CREATOR_TYPE,\
"CURRENCY_TYPE" AS CURRENCY_TYPE,\
"CUSTOM_FIELDS_LONG" AS CUSTOM_FIELDS_LONG,\
"custom1" AS custom1,\
"custom5" AS custom5,\
"custom2" AS custom2,\
"custom3" AS custom3,\
"custom4" AS custom4,\
"custom6" AS custom6,\
"custom7" AS custom7,\
"custom8" AS custom8,\
"DESCRIPTION" AS DESCRIPTION,\
"NAME" AS NAME,\
"NEXT_STEP" AS NEXT_STEP,\
"OPPORTUNITY_TYPE" AS OPPORTUNITY_TYPE,\
"OWNER_ID" AS OWNER_ID,\
"PROBABILITY" AS PROBABILITY,\
"STAGE_ID" AS STAGE_ID,\
"STATE" AS STATE,\
"TOUCHED_AT" AS TOUCHED_AT,\
"UPDATED_AT" AS UPDATED_AT,\
"ID" AS ID,\
"SURROGATE_ID" AS SURROGATE_ID,\
"DML_TYPE" AS DML_TYPE,\
"DML_AT" AS DML_AT,\
"IS_DELETED_IN_APP" AS IS_DELETED_IN_APP,\
"O_ID" AS O_ID,\
"BENTO" AS BENTO,\
"META_UNIQUE_HASH" AS META_UNIQUE_HASH,\
"META_ROW_HASH" AS META_ROW_HASH,\
"META_IS_DELETED" AS META_IS_DELETED,\
"META_INSERT_TIMESTAMP" AS META_INSERT_TIMESTAMP,\
"META_UPDATE_TIMESTAMP" AS META_UPDATE_TIMESTAMP\
FROM RAW.OUTREACH_SHARE.OPPORTUNITIES}