{\rtf1\ansi\ansicpg1252\cocoartf2822
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 ArialMT;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs26\fsmilli13333 \cf0 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 CREATE OR REPLACE DYNAMIC TABLE \{\{CONF\}\}.SALESFORCE_V2.QUOTE_LINE\
TARGET_LAG = DOWNSTREAM\
WAREHOUSE = SF_TRANSFORM_WH\
REFRESH_MODE = INCREMENTAL\
INITIALIZE = ON_SCHEDULE\
DATA_METRIC_SCHEDULE = TRIGGER_ON_CHANGES\
as\
SELECT \
"Id" as ID\
,case when UPPER("IsDeleted") = 'FALSE' THEN FALSE ELSE TRUE END AS IS_DELETED\
,"Name" as NAME\
,"CurrencyIsoCode" as CURRENCY_ISO_CODE\
,TO_TIMESTAMP_TZ(LEFT("CreatedDate",19)) as CREATEDDATE\
,"CreatedById" as CREATEDBYID\
,TO_TIMESTAMP_TZ(LEFT("LastModifiedDate",19)) as LASTMODIFIEDDATE\
,"LastModifiedById" as LASTMODIFIEDBYID\
,"SystemModstamp" as SYSTEMMODSTAMP\
,"SBQQ__Quote__c" as SBQQ__QUOTE__C\
,"SBQQ__AdditionalDiscountAmount__c" as SBQQ__ADDITIONALDISCOUNTAMOUNT__C\
,"SBQQ__AdditionalDiscount__c" as SBQQ__ADDITIONALDISCOUNT__C\
,"SBQQ__AdditionalQuantity__c" as SBQQ__ADDITIONALQUANTITY__C\
,"SBQQ__AllowAssetRefund__c" as SBQQ__ALLOWASSETREFUND__C\
,"SBQQ__BatchQuantity__c" as SBQQ__BATCHQUANTITY__C\
,"SBQQ__BillingFrequency__c" as SBQQ__BILLINGFREQUENCY__C\
,"SBQQ__BillingType__c" as SBQQ__BILLINGTYPE__C\
,"SBQQ__BlockPrice__c" as SBQQ__BLOCKPRICE__C\
,"SBQQ__Bundle__c" as SBQQ__BUNDLE__C\
,"SBQQ__BundledQuantity__c" as SBQQ__BUNDLEDQUANTITY__C\
,"SBQQ__Bundled__c" as SBQQ__BUNDLED__C\
,"SBQQ__CarryoverLine__c" as SBQQ__CARRYOVERLINE__C\
,"SBQQ__ChargeType__c" as SBQQ__CHARGETYPE__C\
,"SBQQ__ComponentCost__c" as SBQQ__COMPONENTCOST__C\
,"SBQQ__ComponentDiscountedByPackage__c" as SBQQ__COMPONENTDISCOUNTEDBYPACKAGE__C\
,"SBQQ__ComponentListTotal__c" as SBQQ__COMPONENTLISTTOTAL__C\
,"SBQQ__ComponentSubscriptionScope__c" as SBQQ__COMPONENTSUBSCRIPTIONSCOPE__C\
,"SBQQ__ComponentTotal__c" as SBQQ__COMPONENTTOTAL__C\
,"SBQQ__ComponentUpliftedByPackage__c" as SBQQ__COMPONENTUPLIFTEDBYPACKAGE__C\
,"SBQQ__ComponentVisibility__c" as SBQQ__COMPONENTVISIBILITY__C\
,"SBQQ__CompoundDiscountRate__c" as SBQQ__COMPOUNDDISCOUNTRATE__C\
,"SBQQ__ConfigurationRequired__c" as SBQQ__CONFIGURATIONREQUIRED__C\
,"SBQQ__ContractedPrice__c" as SBQQ__CONTRACTEDPRICE__C\
,"SBQQ__CostEditable__c" as SBQQ__COSTEDITABLE__C\
,"SBQQ__Cost__c" as SBQQ__COST__C\
,"SBQQ__CustomerPrice__c" as SBQQ__CUSTOMERPRICE__C\
,"SBQQ__CustomerTotal__c" as SBQQ__CUSTOMERTOTAL__C\
,"SBQQ__DefaultSubscriptionTerm__c" as SBQQ__DEFAULTSUBSCRIPTIONTERM__C\
,"SBQQ__Description__c" as SBQQ__DESCRIPTION__C\
,"SBQQ__Dimension__c" as SBQQ__DIMENSION__C\
,"SBQQ__DiscountScheduleType__c" as SBQQ__DISCOUNTSCHEDULETYPE__C\
,"SBQQ__DiscountSchedule__c" as SBQQ__DISCOUNTSCHEDULE__C\
,"SBQQ__DiscountTier__c" as SBQQ__DISCOUNTTIER__C\
,"SBQQ__Discount__c" as SBQQ__DISCOUNT__C\
,"SBQQ__DistributorDiscount__c" as SBQQ__DISTRIBUTORDISCOUNT__C\
,"SBQQ__DynamicOptionId__c" as SBQQ__DYNAMICOPTIONID__C\
,"SBQQ__EarliestValidAmendmentStartDate__c" as SBQQ__EARLIESTVALIDAMENDMENTSTARTDATE__C\
,"SBQQ__EffectiveEndDate__c" as SBQQ__EFFECTIVEENDDATE__C\
,"SBQQ__EffectiveQuantity__c" as SBQQ__EFFECTIVEQUANTITY__C\
,"SBQQ__EffectiveStartDate__c" as SBQQ__EFFECTIVESTARTDATE__C\
,"SBQQ__EffectiveSubscriptionTerm__c" as SBQQ__EFFECTIVESUBSCRIPTIONTERM__C\
,LEFT("SBQQ__EndDate__c",10) as SBQQ__ENDDATE__C\
,"SBQQ__Existing__c" as SBQQ__EXISTING__C\
,"SBQQ__Favorite__c" as SBQQ__FAVORITE__C\
,"SBQQ__GenerateContractedPrice__c" as SBQQ__GENERATECONTRACTEDPRICE__C\
,"SBQQ__GrossProfit__c" as SBQQ__GROSSPROFIT__C\
,"SBQQ__Group__c" as SBQQ__GROUP__C\
,"SBQQ__Guidance__c" as SBQQ__GUIDANCE__C\
,"SBQQ__HasConsumptionSchedule__c" as SBQQ__HASCONSUMPTIONSCHEDULE__C\
,"SBQQ__Hidden__c" as SBQQ__HIDDEN__C\
,"SBQQ__Incomplete__c" as SBQQ__INCOMPLETE__C\
,"SBQQ__ListPrice__c" as SBQQ__LISTPRICE__C\
,"SBQQ__ListTotal__c" as SBQQ__LISTTOTAL__C\
,"SBQQ__MarkupAmount__c" as SBQQ__MARKUPAMOUNT__C\
,"SBQQ__MarkupRate__c" as SBQQ__MARKUPRATE__C\
,"SBQQ__Markup__c" as SBQQ__MARKUP__C\
,"SBQQ__MaximumPrice__c" as SBQQ__MAXIMUMPRICE__C\
,"SBQQ__MinimumPrice__c" as SBQQ__MINIMUMPRICE__C\
,"SBQQ__NetPrice__c" as SBQQ__NETPRICE__C\
,"SBQQ__NetTotal__c" as SBQQ__NETTOTAL__C\
,"SBQQ__NonDiscountable__c" as SBQQ__NONDISCOUNTABLE__C\
,"SBQQ__NonPartnerDiscountable__c" as SBQQ__NONPARTNERDISCOUNTABLE__C\
,"SBQQ__Number__c" as SBQQ__NUMBER__C\
,"SBQQ__OptionDiscountAmount__c" as SBQQ__OPTIONDISCOUNTAMOUNT__C\
,"SBQQ__OptionDiscount__c" as SBQQ__OPTIONDISCOUNT__C\
,"SBQQ__OptionLevel__c" as SBQQ__OPTIONLEVEL__C\
,"SBQQ__OptionType__c" as SBQQ__OPTIONTYPE__C\
,"SBQQ__Optional__c" as SBQQ__OPTIONAL__C\
,"SBQQ__OriginalPrice__c" as SBQQ__ORIGINALPRICE__C\
,"SBQQ__OriginalQuoteLineId__c" as SBQQ__ORIGINALQUOTELINEID__C\
,"SBQQ__OriginalUnitCost__c" as SBQQ__ORIGINALUNITCOST__C\
,"SBQQ__PackageCost__c" as SBQQ__PACKAGECOST__C\
,"SBQQ__PackageListTotal__c" as SBQQ__PACKAGELISTTOTAL__C\
,"SBQQ__PackageProductCode__c" as SBQQ__PACKAGEPRODUCTCODE__C\
,"SBQQ__PackageProductDescription__c" as SBQQ__PACKAGEPRODUCTDESCRIPTION__C\
,"SBQQ__PackageTotal__c" as SBQQ__PACKAGETOTAL__C\
,"SBQQ__PartnerDiscount__c" as SBQQ__PARTNERDISCOUNT__C\
,"SBQQ__PartnerPrice__c" as SBQQ__PARTNERPRICE__C\
,"SBQQ__PartnerTotal__c" as SBQQ__PARTNERTOTAL__C\
,"SBQQ__PreviousSegmentPrice__c" as SBQQ__PREVIOUSSEGMENTPRICE__C\
,"SBQQ__PreviousSegmentUplift__c" as SBQQ__PREVIOUSSEGMENTUPLIFT__C\
,"SBQQ__PriceEditable__c" as SBQQ__PRICEEDITABLE__C\
,"SBQQ__PricebookEntryId__c" as SBQQ__PRICEBOOKENTRYID__C\
,"SBQQ__PricingMethodEditable__c" as SBQQ__PRICINGMETHODEDITABLE__C\
,"SBQQ__PricingMethod__c" as SBQQ__PRICINGMETHOD__C\
,"SBQQ__PriorQuantity__c" as SBQQ__PRIORQUANTITY__C\
,"SBQQ__ProductCode__c" as SBQQ__PRODUCTCODE__C\
,"SBQQ__ProductFamily__c" as SBQQ__PRODUCTFAMILY__C\
,"SBQQ__ProductName__c" as SBQQ__PRODUCTNAME__C\
,"SBQQ__ProductOption__c" as SBQQ__PRODUCTOPTION__C\
,"SBQQ__ProductSubscriptionType__c" as SBQQ__PRODUCTSUBSCRIPTIONTYPE__C\
,"SBQQ__Product__c" as SBQQ__PRODUCT__C\
,"SBQQ__ProrateMultiplier__c" as SBQQ__PRORATEMULTIPLIER__C\
,"SBQQ__ProratedListPrice__c" as SBQQ__PRORATEDLISTPRICE__C\
,"SBQQ__ProratedPrice__c" as SBQQ__PRORATEDPRICE__C\
,"SBQQ__Quantity__c" as SBQQ__QUANTITY__C\
,"SBQQ__RegularPrice__c" as SBQQ__REGULARPRICE__C\
,"SBQQ__RegularTotal__c" as SBQQ__REGULARTOTAL__C\
,"SBQQ__Renewal__c" as SBQQ__RENEWAL__C\
,"SBQQ__RenewedAsset__c" as SBQQ__RENEWEDASSET__C\
,"SBQQ__RenewedSubscription__c" as SBQQ__RENEWEDSUBSCRIPTION__C\
,"SBQQ__RequiredBy__c" as SBQQ__REQUIREDBY__C\
,"SBQQ__SegmentIndex__c" as SBQQ__SEGMENTINDEX__C\
,"SBQQ__SegmentKey__c" as SBQQ__SEGMENTKEY__C\
,"SBQQ__SegmentLabel__c" as SBQQ__SEGMENTLABEL__C\
,"SBQQ__Source__c" as SBQQ__SOURCE__C\
,"SBQQ__SpecialPriceDescription__c" as SBQQ__SPECIALPRICEDESCRIPTION__C\
,"SBQQ__SpecialPriceType__c" as SBQQ__SPECIALPRICETYPE__C\
,"SBQQ__SpecialPrice__c" as SBQQ__SPECIALPRICE__C\
,LEFT("SBQQ__StartDate__c",10) as SBQQ__STARTDATE__C\
,"SBQQ__SubscribedAssetIds__c" as SBQQ__SUBSCRIBEDASSETIDS__C\
,"SBQQ__SubscriptionBase__c" as SBQQ__SUBSCRIPTIONBASE__C\
,"SBQQ__SubscriptionCategory__c" as SBQQ__SUBSCRIPTIONCATEGORY__C\
,"SBQQ__SubscriptionPercent__c" as SBQQ__SUBSCRIPTIONPERCENT__C\
,"SBQQ__SubscriptionPricing__c" as SBQQ__SUBSCRIPTIONPRICING__C\
,"SBQQ__SubscriptionScope__c" as SBQQ__SUBSCRIPTIONSCOPE__C\
,"SBQQ__SubscriptionTargetPrice__c" as SBQQ__SUBSCRIPTIONTARGETPRICE__C\
,"SBQQ__SubscriptionTerm__c" as SBQQ__SUBSCRIPTIONTERM__C\
,"SBQQ__SubscriptionType__c" as SBQQ__SUBSCRIPTIONTYPE__C\
,"SBQQ__TaxCode__c" as SBQQ__TAXCODE__C\
,"SBQQ__Taxable__c" as SBQQ__TAXABLE__C\
,"SBQQ__TermDiscountSchedule__c" as SBQQ__TERMDISCOUNTSCHEDULE__C\
,"SBQQ__TermDiscountTier__c" as SBQQ__TERMDISCOUNTTIER__C\
,"SBQQ__TermDiscount__c" as SBQQ__TERMDISCOUNT__C\
,"SBQQ__TotalDiscountAmount__c" as SBQQ__TOTALDISCOUNTAMOUNT__C\
,"SBQQ__TotalDiscountRate__c" as SBQQ__TOTALDISCOUNTRATE__C\
,"SBQQ__UnitCost__c" as SBQQ__UNITCOST__C\
,"SBQQ__UnproratedNetPrice__c" as SBQQ__UNPRORATEDNETPRICE__C\
,"SBQQ__UpgradedAsset__c" as SBQQ__UPGRADEDASSET__C\
,"SBQQ__UpgradedQuantity__c" as SBQQ__UPGRADEDQUANTITY__C\
,"SBQQ__UpgradedSubscription__c" as SBQQ__UPGRADEDSUBSCRIPTION__C\
,"SBQQ__UpliftAmount__c" as SBQQ__UPLIFTAMOUNT__C\
,"SBQQ__Uplift__c" as SBQQ__UPLIFT__C\
,"SBQQ__VolumeDiscount__c" as SBQQ__VOLUMEDISCOUNT__C\
,"AnnualListPrice__c" as ANNUALLISTPRICE__C\
,"AnnualNetUnitPrice__c" as ANNUALNETUNITPRICE__C\
,"CPQ_MRR__c" as CPQ_MRR__C\
,"DSSProduct__c" as DSSPRODUCT__C\
,"IgnoreLine__c" as IGNORELINE__C\
,"NetFinalPrice__c" as NETFINALPRICE__C\
,"NetNewQuantity__c" as NETNEWQUANTITY__C\
,"ODQuantity__c" as ODQUANTITY__C\
,"Product_Sub_Familly__c" as PRODUCT_SUB_FAMILLY__C\
,"QuantityUnitOfMeasure__c" as QUANTITYUNITOFMEASURE__C\
,"Quantity_Editable__c" as QUANTITY_EDITABLE__C\
,"Tech_IsNode__c" as TECH_ISNODE__C\
,"Tech_PriorQuantity__c" as TECH_PRIORQUANTITY__C\
,"Tech_Quantity__c" as TECH_QUANTITY__C\
,"Tech_QuoteLineARR__c" as TECH_QUOTELINEARR__C\
,"Tech_QuoteStartDateIdentical__c" as TECH_QUOTESTARTDATEIDENTICAL__C\
,"Tech_ShowQuoteLinesforAmendment__c" as TECH_SHOWQUOTELINESFORAMENDMENT__C\
,"Sellability__c" as SELLABILITY__C\
,"Effective_End_Datefx__c" as EFFECTIVE_END_DATEFX__C\
,"Effective_Start_Datefx__c" as EFFECTIVE_START_DATEFX__C\
,"NetSuite_Product_Code__c" as NETSUITE_PRODUCT_CODE__C\
,"Technical_Services_Availability_Date__c" as TECHNICAL_SERVICES_AVAILABILITY_DATE__C\
,"Technical_Services_Availability_Datefx__c" as TECHNICAL_SERVICES_AVAILABILITY_DATEFX__C\
,"Technical_Services_Expiry_Date__c" as TECHNICAL_SERVICES_EXPIRY_DATE__C\
,"Technical_Services_Expiry_Datefx__c" as TECHNICAL_SERVICES_EXPIRY_DATEFX__C\
,"Pricing_Year__c" as PRICING_YEAR__C\
,"Online_product__c" as ONLINE_PRODUCT__C\
,"Level_4_Approval_Required__c" as LEVEL_4_APPROVAL_REQUIRED__C\
,"Annual_Net_Unit_Price_Override__c" as ANNUAL_NET_UNIT_PRICE_OVERRIDE__C\
,"Level_3_Approval_Required__c" as LEVEL_3_APPROVAL_REQUIRED__C\
,"Custom_Technical_Services_Dates__c" as CUSTOM_TECHNICAL_SERVICES_DATES__C\
,"Decimal_flag__c" as DECIMAL_FLAG__C\
,"Legacy_requires_approval__c" as LEGACY_REQUIRES_APPROVAL__C\
,"Service_Controlled__c" as SERVICE_CONTROLLED__C\
,"Service_Controlled_Set_2__c" as SERVICE_CONTROLLED_SET_2__C\
,"Allowed_for_Cloud__c" as ALLOWED_FOR_CLOUD__C\
,"CPQ_Generated__c" as CPQ_GENERATED__C\
,"META_UNIQUE_HASH" as META_UNIQUE_HASH\
,"META_ROW_HASH" as META_ROW_HASH\
,"META_IS_DELETED" as META_IS_DELETED\
,"META_INSERT_TIMESTAMP" as META_INSERT_TIMESTAMP\
,"META_UPDATE_TIMESTAMP" as META_UPDATE_TIMESTAMP\
\
FROM RAW.SALESFORCE_DSS.QUOTE_LINE_ITEM}