{\rtf1\ansi\ansicpg1252\cocoartf2822
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 ArialMT;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs26\fsmilli13333 \cf0 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 CREATE OR REPLACE DYNAMIC TABLE \{\{CONF\}\}.SALESFORCE_V2.USE_CASE\
TARGET_LAG = DOWNSTREAM\
WAREHOUSE = SF_TRANSFORM_WH\
REFRESH_MODE = INCREMENTAL\
INITIALIZE = ON_SCHEDULE\
DATA_METRIC_SCHEDULE = TRIGGER_ON_CHANGES\
as\
SELECT\
"Id" AS "ID",\
case when UPPER("IsDeleted") = 'FALSE' THEN FALSE ELSE TRUE END AS "ISDELETED",\
"Name" AS "NAME",\
"CurrencyIsoCode" AS "CURRENCYISOCODE",\
"CreatedDate" AS "CREATEDDATE",\
"CreatedById" AS "CREATEDBYID",\
"LastModifiedDate" AS "LASTMODIFIEDDATE",\
"LastModifiedById" AS "LASTMODIFIEDBYID",\
cast("SystemModstamp" as text) AS "SYSTEMMODSTAMP",\
"LastActivityDate" AS "LASTACTIVITYDATE",\
"LastViewedDate" AS "LASTVIEWEDDATE",\
"LastReferencedDate" AS "LASTREFERENCEDDATE",\
"Account__c" AS "ACCOUNT__C",\
"Opportunity__c" AS "OPPORTUNITY__C",\
"Integration_Level__c" AS "INTEGRATION_LEVEL__C",\
"Benefitting_Business_Function__c" AS "BENEFITTING_BUSINESS_FUNCTION__C",\
"Business_Solution__c" AS "BUSINESS_SOLUTION__C",\
"Stage__c" AS "STAGE__C",\
"Use_Case_Description__c" AS "USE_CASE_DESCRIPTION__C",\
"Analysts__c" AS "ANALYSTS__C",\
"Business_Impact__c" AS "BUSINESS_IMPACT__C",\
"Domain__c" AS "DOMAIN__C",\
"Implementation_Use_Case__c" AS "IMPLEMENTATION_USE_CASE__C",\
"Value_Range__c" AS "VALUE_RANGE__C",\
"Implementation_Manager__c" AS "IMPLEMENTATION_MANAGER__C",\
"Detailed_Documentation__c" AS "DETAILED_DOCUMENTATION__C",\
"Substainability_Subject__c" AS "SUBSTAINABILITY_SUBJECT__C",\
"Related_to_won_oppie__c" AS "RELATED_TO_WON_OPPIE__C",\
"Technical_Dimension__c" AS "TECHNICAL_DIMENSION__C",\
"Value_Type__c" AS "VALUE_TYPE__C",\
"Use_Cases_Primary_Contact__c" AS "USE_CASES_PRIMARY_CONTACT__C",\
META_UNIQUE_HASH AS "META_UNIQUE_HASH",\
META_ROW_HASH AS "META_ROW_HASH",\
META_IS_DELETED AS "META_IS_DELETED",\
CONVERT_TIMEZONE('UTC',META_INSERT_TIMESTAMP) AS "META_INSERT_TIMESTAMP",\
CONVERT_TIMEZONE('UTC',META_UPDATE_TIMESTAMP) AS "META_UPDATE_TIMESTAMP",\
METADATA$ACTION AS "METADATA$ACTION",\
METADATA$ISUPDATE AS "METADATA$ISUPDATE",\
METADATA$ROW_ID AS "METADATA$ROW_ID",\
CONVERT_TIMEZONE('UTC',METADATA_SNAPSHOT_DATETIME) AS "METADATA_SNAPSHOT_DATETIME",\
METADATA_UNIQUE_ID AS "METADATA_UNIQUE_ID",\
CONVERT_TIMEZONE('UTC',METADATA_RECORD_START) AS "METADATA_RECORD_START",\
CONVERT_TIMEZONE('UTC',METADATA_RECORD_END) AS "METADATA_RECORD_END",\
METADATA_ACTIVE_FLAG AS "METADATA_ACTIVE_FLAG"\
FROM RAW.SNAPSHOT_SALESFORCE_DSS.V_SNAPSHOT_USE_CASE\
WHERE METADATA_RECORD_START >= '2023-10-23T00:00:00.000Z' \
UNION ALL\
SELECT \
"ID",\
case when UPPER("ISDELETED") = 'FALSE' THEN FALSE ELSE TRUE END AS \
"ISDELETED",\
"NAME",\
"CURRENCYISOCODE",\
CAST("CREATEDDATE" AS TEXT) AS CREATEDDATE,\
"CREATEDBYID",\
CAST("LASTMODIFIEDDATE" AS TEXT) AS LASTMODIFIEDDATE,\
"LASTMODIFIEDBYID",\
cast("SYSTEMMODSTAMP" as text) AS "SYSTEMMODSTAMP",\
"LASTACTIVITYDATE",\
"LASTVIEWEDDATE",\
"LASTREFERENCEDDATE",\
"ACCOUNT__C",\
"OPPORTUNITY__C",\
"INTEGRATION_LEVEL__C",\
"BENEFITTING_BUSINESS_FUNCTION__C",\
"BUSINESS_SOLUTION__C",\
"STAGE__C",\
"USE_CASE_DESCRIPTION__C",\
"ANALYSTS__C",\
"BUSINESS_IMPACT__C",\
"DOMAIN__C",\
"IMPLEMENTATION_USE_CASE__C",\
"VALUE_RANGE__C",\
"IMPLEMENTATION_MANAGER__C",\
"DETAILED_DOCUMENTATION__C",\
"SUBSTAINABILITY_SUBJECT__C",\
"RELATED_TO_WON_OPPIE__C",\
"TECHNICAL_DIMENSION__C",\
"VALUE_TYPE__C",\
"USE_CASES_PRIMARY_CONTACT__C",\
"META_UNIQUE_HASH",\
"META_ROW_HASH",\
"META_IS_DELETED",\
CAST("META_INSERT_TIMESTAMP" as TIMESTAMP_TZ(9)),\
CAST("META_UPDATE_TIMESTAMP" as TIMESTAMP_TZ(9)),\
CAST("METADATA$ACTION" AS VARCHAR(16777216)),\
CAST("METADATA$ISUPDATE" AS VARCHAR(16777216)),\
CAST("METADATA$ROW_ID" AS VARCHAR(16777216)),\
CAST("METADATA_SNAPSHOT_DATETIME" as TIMESTAMP_TZ(9)),\
CAST("METADATA_UNIQUE_ID" AS VARCHAR(36)),\
CAST("METADATA_RECORD_START" as TIMESTAMP_TZ(9)),\
CAST("METADATA_RECORD_END" as TIMESTAMP_TZ(9)),\
"METADATA_ACTIVE_FLAG"\
FROM RAW.SALESFORCE_DSS.USE_CASE_MIGRATED}