{\rtf1\ansi\ansicpg1252\cocoartf2822
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 ArialMT;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs26\fsmilli13333 \cf0 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 CREATE OR REPLACE DYNAMIC TABLE \{\{CONF\}\}.SALESFORCE_V2.QUOTE\
TARGET_LAG = DOWNSTREAM\
WAREHOUSE = SF_TRANSFORM_WH\
REFRESH_MODE = INCREMENTAL\
INITIALIZE = ON_SCHEDULE\
DATA_METRIC_SCHEDULE = TRIGGER_ON_CHANGES\
as\
SELECT\
"Id" as ID\
,"OwnerId" as OWNER_ID\
,case when UPPER("IsDeleted") = 'FALSE' THEN FALSE ELSE TRUE END AS IS_DELETED\
,"Name" as NAME\
,"CurrencyIsoCode" as CURRENCY_ISO_CODE\
,"RecordTypeId" as RECORDTYPEID\
,LEFT("CreatedDate",19)::DATE as CREATEDDATE\
,"CreatedById" as CREATEDBYID\
,LEFT("LastModifiedDate",19)::DATE as LASTMODIFIEDDATE\
,"LastModifiedById" as LASTMODIFIEDBYID\
,"SystemModstamp" as SYSTEMMODSTAMP\
,"LastActivityDate" as LASTACTIVITYDATE\
,"LastViewedDate" as LASTVIEWEDDATE\
,"LastReferencedDate" as LASTREFERENCEDDATE\
,"SBQQ__Account__c" as SBQQ__ACCOUNT__C\
,"SBQQ__AdditionalDiscountAmount__c" as SBQQ__ADDITIONALDISCOUNTAMOUNT__C\
,"SBQQ__AverageCustomerDiscount__c" as SBQQ__AVERAGECUSTOMERDISCOUNT__C\
,"SBQQ__AveragePartnerDiscount__c" as SBQQ__AVERAGEPARTNERDISCOUNT__C\
,"SBQQ__BillingCity__c" as SBQQ__BILLINGCITY__C\
,"SBQQ__BillingCountry__c" as SBQQ__BILLINGCOUNTRY__C\
,"SBQQ__BillingFrequency__c" as SBQQ__BILLINGFREQUENCY__C\
,"SBQQ__BillingName__c" as SBQQ__BILLINGNAME__C\
,"SBQQ__BillingPostalCode__c" as SBQQ__BILLINGPOSTALCODE__C\
,"SBQQ__BillingState__c" as SBQQ__BILLINGSTATE__C\
,"SBQQ__BillingStreet__c" as SBQQ__BILLINGSTREET__C\
,"SBQQ__ConsumptionRateOverride__c" as SBQQ__CONSUMPTIONRATEOVERRIDE__C\
,"SBQQ__ContractingMethod__c" as SBQQ__CONTRACTINGMETHOD__C\
,"SBQQ__CustomerDiscount__c" as SBQQ__CUSTOMERDISCOUNT__C\
,"SBQQ__DaysQuoteOpen__c" as SBQQ__DAYSQUOTEOPEN__C\
,"SBQQ__DefaultTemplate__c" as SBQQ__DEFAULTTEMPLATE__C\
,"SBQQ__DeliveryMethod__c" as SBQQ__DELIVERYMETHOD__C\
,"SBQQ__DistributorDiscount__c" as SBQQ__DISTRIBUTORDISCOUNT__C\
,"SBQQ__Distributor__c" as SBQQ__DISTRIBUTOR__C\
,"SBQQ__DocumentStatus__c" as SBQQ__DOCUMENTSTATUS__C\
,"SBQQ__EmailTemplateId__c" as SBQQ__EMAILTEMPLATEID__C\
,"SBQQ__EndDate__c" as SBQQ__ENDDATE__C\
,"SBQQ__ExpirationDate__c" as SBQQ__EXPIRATIONDATE__C\
,"SBQQ__FirstSegmentTermEndDate__c" as SBQQ__FIRSTSEGMENTTERMENDDATE__C\
,"SBQQ__GenerateContractedPrice__c" as SBQQ__GENERATECONTRACTEDPRICE__C\
,"SBQQ__Introduction__c" as SBQQ__INTRODUCTION__C\
,"SBQQ__Key__c" as SBQQ__KEY__C\
,"SBQQ__LastCalculatedOn__c" as SBQQ__LASTCALCULATEDON__C\
,"SBQQ__LastSavedOn__c" as SBQQ__LASTSAVEDON__C\
,"SBQQ__LineItemsGrouped__c" as SBQQ__LINEITEMSGROUPED__C\
,"SBQQ__LineItemsPrinted__c" as SBQQ__LINEITEMSPRINTED__C\
,"SBQQ__MarkupRate__c" as SBQQ__MARKUPRATE__C\
,"SBQQ__MasterContract__c" as SBQQ__MASTERCONTRACT__C\
,"SBQQ__MasterEvergreenContract__c" as SBQQ__MASTEREVERGREENCONTRACT__C\
,"SBQQ__Notes__c" as SBQQ__NOTES__C\
,"SBQQ__Opportunity2__c" as SBQQ__OPPORTUNITY2__C\
,"SBQQ__OrderByQuoteLineGroup__c" as SBQQ__ORDERBYQUOTELINEGROUP__C\
,"SBQQ__OrderBy__c" as SBQQ__ORDERBY__C\
,"SBQQ__OrderGroupID__c" as SBQQ__ORDERGROUPID__C\
,"SBQQ__Ordered__c" as SBQQ__ORDERED__C\
,"SBQQ__OriginalQuote__c" as SBQQ__ORIGINALQUOTE__C\
,"SBQQ__PaperSize__c" as SBQQ__PAPERSIZE__C\
,"SBQQ__PartnerDiscount__c" as SBQQ__PARTNERDISCOUNT__C\
,"SBQQ__Partner__c" as SBQQ__PARTNER__C\
,"SBQQ__PaymentTerms__c" as SBQQ__PAYMENTTERMS__C\
,"SBQQ__PriceBook__c" as SBQQ__PRICEBOOK__C\
,"SBQQ__PricebookId__c" as SBQQ__PRICEBOOKID__C\
,"SBQQ__PrimaryContact__c" as SBQQ__PRIMARYCONTACT__C\
,"SBQQ__Primary__c"::BOOLEAN as SBQQ__PRIMARY__C\
,"SBQQ__ProrationDayOfMonth__c" as SBQQ__PRORATIONDAYOFMONTH__C\
,"SBQQ__QuoteLanguage__c" as SBQQ__QUOTELANGUAGE__C\
,"SBQQ__QuoteProcessId__c" as SBQQ__QUOTEPROCESSID__C\
,"SBQQ__QuoteTemplateId__c" as SBQQ__QUOTETEMPLATEID__C\
,"SBQQ__RenewalTerm__c" as SBQQ__RENEWALTERM__C\
,"SBQQ__RenewalUpliftRate__c" as SBQQ__RENEWALUPLIFTRATE__C\
,"SBQQ__SalesRep__c" as SBQQ__SALESREP__C\
,"SBQQ__ShippingCity__c" as SBQQ__SHIPPINGCITY__C\
,"SBQQ__ShippingCountry__c" as SBQQ__SHIPPINGCOUNTRY__C\
,"SBQQ__ShippingName__c" as SBQQ__SHIPPINGNAME__C\
,"SBQQ__ShippingPostalCode__c" as SBQQ__SHIPPINGPOSTALCODE__C\
,"SBQQ__ShippingState__c" as SBQQ__SHIPPINGSTATE__C\
,"SBQQ__ShippingStreet__c" as SBQQ__SHIPPINGSTREET__C\
,"SBQQ__Source__c" as SBQQ__SOURCE__C\
,"SBQQ__StartDate__c" as SBQQ__STARTDATE__C\
,"SBQQ__Status__c" as SBQQ__STATUS__C\
,"SBQQ__SubscriptionTerm__c" as SBQQ__SUBSCRIPTIONTERM__C\
,"SBQQ__TargetCustomerAmount__c" as SBQQ__TARGETCUSTOMERAMOUNT__C\
,"SBQQ__TotalCustomerDiscountAmount__c" as SBQQ__TOTALCUSTOMERDISCOUNTAMOUNT__C\
,"SBQQ__Type__c" as SBQQ__TYPE__C\
,"SBQQ__Uncalculated__c" as SBQQ__UNCALCULATED__C\
,"SBQQ__Unopened__c" as SBQQ__UNOPENED__C\
,"SBQQ__WatermarkShown__c" as SBQQ__WATERMARKSHOWN__C\
,"SBQQ__CustomerAmount__c" as SBQQ__CUSTOMERAMOUNT__C\
,"SBQQ__LineItemCount__c" as SBQQ__LINEITEMCOUNT__C\
,"SBQQ__ListAmount__c" as SBQQ__LISTAMOUNT__C\
,"SBQQ__NetAmount__c" as SBQQ__NETAMOUNT__C\
,"SBQQ__RegularAmount__c" as SBQQ__REGULARAMOUNT__C\
,"ARR__c" as ARR__C\
,"ATR__c" as ATR__C\
,"AccountName__c" as ACCOUNTNAME__C\
,"AdditionalPurchase__c" as ADDITIONALPURCHASE__C\
,"AdditionalTerms__c" as ADDITIONALTERMS__C\
,"Approval_Reason__c" as APPROVAL_REASON__C\
,"Approved_by_Deal_Desk__c" as APPROVED_BY_DEAL_DESK__C\
,"Approver__c" as APPROVER__C\
,"AverageARR__c" as AVERAGEARR__C\
,"Avg_Discount_on_Licenses__c" as AVG_DISCOUNT_ON_LICENSES__C\
,"BillToTaxIDVATNumber__c" as BILLTOTAXIDVATNUMBER__C\
,"BillingContactEmail__c" as BILLINGCONTACTEMAIL__C\
,"BillingContact__c" as BILLINGCONTACT__C\
,"BillingType__c" as BILLINGTYPE__C\
,"BusinessJustification__c" as BUSINESSJUSTIFICATION__C\
,"CPQApprovalDiscount__c" as CPQAPPROVALDISCOUNT__C\
,"CPQTech_In_Approval__c" as CPQTECH_IN_APPROVAL__C\
,"CPQ_Approver__c" as CPQ_APPROVER__C\
,"CPQ_Average_Discount_on_License__c" as CPQ_AVERAGE_DISCOUNT_ON_LICENSE__C\
,"CPQ_Business_Justification__c" as CPQ_BUSINESS_JUSTIFICATION__C\
,"CPQ_POD__c" as CPQ_POD__C\
,"CPQ_RVP__c" as CPQ_RVP__C\
,"CPQ_RenewalUplift__c" as CPQ_RENEWALUPLIFT__C\
,"CPQ_Subscription_Term__c" as CPQ_SUBSCRIPTION_TERM__C\
,"CPQ_TopCustomApprovalDiscount__c" as CPQ_TOPCUSTOMAPPROVALDISCOUNT__C\
,"CPQ_VPFirstApprover__c" as CPQ_VPFIRSTAPPROVER__C\
,"CPQ_VP__c" as CPQ_VP__C\
,"CaseStudyMarketingClause__c"::BOOLEAN as CASESTUDYMARKETINGCLAUSE__C\
,"Contracted_Node__c" as CONTRACTED_NODE__C\
,"CustomAdditionalPurchase__c" as CUSTOMADDITIONALPURCHASE__C\
,"CustomBilling__c" as CUSTOMBILLING__C\
,"CustomProductPackageBundleComments__c" as CUSTOMPRODUCTPACKAGEBUNDLECOMMENTS__C\
,"CustomProductPackageBundle__c" as CUSTOMPRODUCTPACKAGEBUNDLE__C\
,"DataikuEntityAddress__c" as DATAIKUENTITYADDRESS__C\
,"DataikuEntitySiret__c" as DATAIKUENTITYSIRET__C\
,"DataikuEntityVAT__c" as DATAIKUENTITYVAT__C\
,"DataikuEntity__c" as DATAIKUENTITY__C\
,"DealStructure__c" as DEALSTRUCTURE__C\
,"Non_Standard_Structure_Approval__c" as NON_STANDARD_STRUCTURE_APPROVAL__C\
,"Non_Standard_Structure_Approval_Details__c" as NON_STANDARD_STRUCTURE_APPROVAL_DETAILS__C\
,"Duration_OLD__c" as DURATION_OLD__C\
,"EditLinesFieldSetName__c" as EDITLINESFIELDSETNAME__C\
,"EditionType__c" as EDITIONTYPE__C\
,TO_TIMESTAMP_TZ(LEFT("EffectiveDate__c",19)) as EFFECTIVEDATE__C\
,"FirstInvoiceAmount__c" as FIRSTINVOICEAMOUNT__C\
,"List_Total_User_Licenses__c" as LIST_TOTAL_USER_LICENSES__C\
,"LogoMarketingCause__c"::BOOLEAN as LOGOMARKETINGCAUSE__C\
,"MLALanguage__c" as MLALANGUAGE__C\
,"MLAWorkflow__c" as MLAWORKFLOW__C\
,"MLA_Date__c" as MLA_DATE__C\
,"MLA_account__c" as MLA_ACCOUNT__C\
,"MSPComments__c" as MSPCOMMENTS__C\
,"MSP__c" as MSP__C\
,"MarketplaceComments__c" as MARKETPLACECOMMENTS__C\
,"Marketplace_Migration__c" as MARKETPLACE_MIGRATION__C\
,"Marketplace_from_Opportunity__c" as MARKETPLACE_FROM_OPPORTUNITY__C\
,"NNARR__c" as NNARR__C\
,"NameMarketingClause__c"::BOOLEAN as NAMEMARKETINGCLAUSE__C\
,"NetTotalwOneTime__c" as NETTOTALWONETIME__C\
,"Net_Total_User_Licenses__c" as NET_TOTAL_USER_LICENSES__C\
,"NoUpliftCap__c"::BOOLEAN as NOUPLIFTCAP__C\
,"ODDisplayOption__c" as ODDISPLAYOPTION__C\
,"ODWorkflow__c" as ODWORKFLOW__C\
,"OEMComments__c" as OEMCOMMENTS__C\
,"OEM__c" as OEM__C\
,"OneTimeDiscountAmount__c" as ONETIMEDISCOUNTAMOUNT__C\
,"OneTimeDiscount__c" as ONETIMEDISCOUNT__C\
,"Opt_Out_Date__c" as OPT_OUT_DATE__C\
,"POD_Approver__c" as POD_APPROVER__C\
,"PORequested__c" as POREQUESTED__C\
,"PilotPhasePOCIncludedComments__c" as PILOTPHASEPOCINCLUDEDCOMMENTS__C\
,"PilotPhasePOCIncluded__c" as PILOTPHASEPOCINCLUDED__C\
,"PressReleaseMarketingClause__c"::BOOLEAN as PRESSRELEASEMARKETINGCLAUSE__C\
,"PrimaryContactEmail__c" as PRIMARYCONTACTEMAIL__C\
,"QuoteName__c" as QUOTENAME__C\
,"RVP_Approver__c" as RVP_APPROVER__C\
,"RecurringDiscount__c" as RECURRINGDISCOUNT__C\
,"RecurringProductsOnQuote__c" as RECURRINGPRODUCTSONQUOTE__C\
,"ReferenceCallMarketingClause__c"::BOOLEAN as REFERENCECALLMARKETINGCLAUSE__C\
,"RefundAmount__c" as REFUNDAMOUNT__C\
,"RelatedListButton__c" as RELATEDLISTBUTTON__C\
,"RenewalARR__c" as RENEWALARR__C\
,"RenewalType__c" as RENEWALTYPE__C\
,"Reseller_Deal__c" as RESELLER_DEAL__C\
,"SVP_Approver__c" as SVP_APPROVER__C\
,"ServiceQuote__c" as SERVICEQUOTE__C\
,"ServicesProductsOnQuote__c" as SERVICESPRODUCTSONQUOTE__C\
,"ShowWatermarkDraftInreview__c" as SHOWWATERMARKDRAFTINREVIEW__C\
,LEFT("SignatureDate__c",19)::DATE as SIGNATUREDATE__C\
,"SpecialTerms__c" as SPECIALTERMS__C\
,"TaxIDVAT__c" as TAXIDVAT__C\
,"TechOTD__c" as TECHOTD__C\
,"TechRecurringProductsAndDiscount__c" as TECHRECURRINGPRODUCTSANDDISCOUNT__C\
,"Tech_AdditionalPurchaseCustom__c" as TECH_ADDITIONALPURCHASECUSTOM__C\
,"Tech_AdditionalPurchaseSamePrice__c" as TECH_ADDITIONALPURCHASESAMEPRICE__C\
,"Tech_Approval_discount__c" as TECH_APPROVAL_DISCOUNT__C\
,"Tech_AutoRenewal__c" as TECH_AUTORENEWAL__C\
,"Tech_AverageARRQuoteLineGroup__c" as TECH_AVERAGEARRQUOTELINEGROUP__C\
,"Tech_BillingContactName__c" as TECH_BILLINGCONTACTNAME__C\
,"Tech_CPQMarketingClauseChecked__c" as TECH_CPQMARKETINGCLAUSECHECKED__C\
,"Tech_CaseStudyMktgClause__c" as TECH_CASESTUDYMKTGCLAUSE__C\
,"Tech_Clause_removed__c" as TECH_CLAUSE_REMOVED__C\
,"Tech_CountBusinessEditionLines__c" as TECH_COUNTBUSINESSEDITIONLINES__C\
,"Tech_CountDiscoverEditionLines__c" as TECH_COUNTDISCOVEREDITIONLINES__C\
,"Tech_CountEnterpriseEditionLines__c" as TECH_COUNTENTERPRISEEDITIONLINES__C\
,"Tech_CustomBilling__c" as TECH_CUSTOMBILLING__C\
,"Tech_ExistingMLA__c" as TECH_EXISTINGMLA__C\
,"Tech_FinanceDOA_alerted__c" as TECH_FINANCEDOA_ALERTED__C\
,"Tech_FirstInvoice12Months__c" as TECH_FIRSTINVOICE12MONTHS__C\
,"Tech_HideTermsforAmendment__c" as TECH_HIDETERMSFORAMENDMENT__C\
,"Tech_ListTotalRecurring__c" as TECH_LISTTOTALRECURRING__C\
,"Tech_LogoMktgClause__c" as TECH_LOGOMKTGCLAUSE__C\
,"Tech_Marketing_PublicityTitle__c" as TECH_MARKETING_PUBLICITYTITLE__C\
,"Tech_NameMktgClause__c" as TECH_NAMEMKTGCLAUSE__C\
,"Tech_NegociatedMLA__c" as TECH_NEGOCIATEDMLA__C\
,"Tech_NetTotalOneTime__c" as TECH_NETTOTALONETIME__C\
,"Tech_NetTotalRecurring__c" as TECH_NETTOTALRECURRING__C\
,"Tech_NumberRecurringProducts__c" as TECH_NUMBERRECURRINGPRODUCTS__C\
,"Tech_NumberServicesProducts__c" as TECH_NUMBERSERVICESPRODUCTS__C\
,"Tech_OnlyShowForAmendment__c" as TECH_ONLYSHOWFORAMENDMENT__C\
,"Tech_PORequested__c" as TECH_POREQUESTED__C\
,"Tech_PressReleaseMktgClause__c" as TECH_PRESSRELEASEMKTGCLAUSE__C\
,"Tech_QuoteNameAutoNumber__c" as TECH_QUOTENAMEAUTONUMBER__C\
,"Tech_QuoteNumberforOD__c" as TECH_QUOTENUMBERFOROD__C\
,"Tech_RecurringProductsNoDiscount__c" as TECH_RECURRINGPRODUCTSNODISCOUNT__C\
,"Tech_ReferenceCallMktgClause__c" as TECH_REFERENCECALLMKTGCLAUSE__C\
,"Tech_RunningUserProfile__c" as TECH_RUNNINGUSERPROFILE__C\
,"Tech_SalesRunningUserProfile__c" as TECH_SALESRUNNINGUSERPROFILE__C\
,"Tech_SignatureBlock__c" as TECH_SIGNATUREBLOCK__C\
,"Tech_SpecialTerms__c" as TECH_SPECIALTERMS__C\
,"Tech_URLMLA__c" as TECH_URLMLA__C\
,"Tech_WithCap__c" as TECH_WITHCAP__C\
,"Tech_WithoutAutoRenewal__c" as TECH_WITHOUTAUTORENEWAL__C\
,"Tech_WithoutCap__c" as TECH_WITHOUTCAP__C\
,"TechnicalServicesExpirationDate__c" as TECHNICALSERVICESEXPIRATIONDATE__C\
,"TrueUpModelComments__c" as TRUEUPMODELCOMMENTS__C\
,"TrueUpModel__c" as TRUEUPMODEL__C\
,"UpsellDownsellvsPriorYear__c" as UPSELLDOWNSELLVSPRIORYEAR__C\
,"VP_Approver__c" as VP_APPROVER__C\
,"Opportunity_Stage__c" as OPPORTUNITY_STAGE__C\
,"Reporting_Sales_Territory__c" as REPORTING_SALES_TERRITORY__C\
,"Opportunity_Type__c" as OPPORTUNITY_TYPE__C\
,"ExpirationDatefx__c" as EXPIRATIONDATEFX__C\
,"Ironclad_Reseller_Deal__c" as IRONCLAD_RESELLER_DEAL__C\
,"Ironclad_PO_Requested__c" as IRONCLAD_PO_REQUESTED__C\
,"Ironclad_No_Renewal_Uplift_Cap__c" as IRONCLAD_NO_RENEWAL_UPLIFT_CAP__C\
,"Ironclad_Name_Marketing_Clause__c" as IRONCLAD_NAME_MARKETING_CLAUSE__C\
,"Ironclad_Logo_Marketing_Clause__c" as IRONCLAD_LOGO_MARKETING_CLAUSE__C\
,"Ironclad_Case_Study_Marketing_Clause__c" as IRONCLAD_CASE_STUDY_MARKETING_CLAUSE__C\
,"Ironclad_Press_Release_MKT_Clause__c" as IRONCLAD_PRESS_RELEASE_MKT_CLAUSE__C\
,"Ironclad_Reference_Call_MKT_Clause__c" as IRONCLAD_REFERENCE_CALL_MKT_CLAUSE__C\
,TO_TIMESTAMP_TZ(LEFT("ApprovalSubmittedDate__c",19)) as APPROVALSUBMITTEDDATE__C\
,"Approval_Pending_Since__c" as APPROVAL_PENDING_SINCE__C\
,"Approval_Status__c" as APPROVAL_STATUS__C\
,"ApprovedDate__c" as APPROVEDDATE__C\
,"CRO_Approval_Date__c" as CRO_APPROVAL_DATE__C\
,"Current_Step_Pending_Since__c" as CURRENT_STEP_PENDING_SINCE__C\
,"Deal_Desk_Final_Approval_Date__c" as DEAL_DESK_FINAL_APPROVAL_DATE__C\
,"Deal_Desk_First_Approval_Date__c" as DEAL_DESK_FIRST_APPROVAL_DATE__C\
,"Latest_Step_TimeStamp__c" as LATEST_STEP_TIMESTAMP__C\
,TO_TIMESTAMP_TZ(LEFT("POD_Approval_Date__c",19)) as POD_APPROVAL_DATE__C\
,"Quote_Approval_Pending_Since__c" as QUOTE_APPROVAL_PENDING_SINCE__C\
,TO_TIMESTAMP_TZ(LEFT("RVP_Approval_Date__c",19)) as RVP_APPROVAL_DATE__C\
,TO_TIMESTAMP_TZ(LEFT("SVP_Approval_Date__c",19)) as SVP_APPROVAL_DATE__C\
,"Time_in_Current_Step__c" as TIME_IN_CURRENT_STEP__C\
,"Total_Approval_Time__c" as TOTAL_APPROVAL_TIME__C\
,"VP_Approval_Date__c" as VP_APPROVAL_DATE__C\
,"Tech_InReviewSalesProfile__c" as TECH_INREVIEWSALESPROFILE__C\
,"URL_MLA_text__c" as URL_MLA_TEXT__C\
,"URL_MLA_text_part_two__c" as URL_MLA_TEXT_PART_TWO__C\
,"CPQTechSubsTerm__c" as CPQTECHSUBSTERM__C\
,"MLA_Datefx__c" as MLA_DATEFX__C\
,"SignatureDatefx__c" as SIGNATUREDATEFX__C\
,"TechnicalServicesExpirationDatefx__c" as TECHNICALSERVICESEXPIRATIONDATEFX__C\
,"Tech_Contains_Legacy_SKUs__c" as TECH_CONTAINS_LEGACY_SKUS__C\
,"ARR_TCV__c" as ARR_TCV__C\
,"Duration__c" as DURATION__C\
,"Duration_TEMP__c" as DURATION_TEMP__C\
,"AA_ARR__c" as AA_ARR__C\
,"ARR_TEMP__c" as ARR_TEMP__C\
,"Online_Quote__c" as ONLINE_QUOTE__C\
,"ChargeBee_Quote_ID__c" as CHARGEBEE_QUOTE_ID__C\
,"AARR__c" as AARR__C\
,"Quote_Line_Groups_Count__c" as QUOTE_LINE_GROUPS_COUNT__C\
,"Opportunity_ID__c" as OPPORTUNITY_ID__C\
,"Opportunity_Close_Date__c" as OPPORTUNITY_CLOSE_DATE__C\
,"Has_Level_3_Approval_Product__c" as HAS_LEVEL_3_APPROVAL_PRODUCT__C\
,"Has_Level_4_Approval_Product__c" as HAS_LEVEL_4_APPROVAL_PRODUCT__C\
,"Partnerships_Approval_Date__c" as PARTNERSHIPS_APPROVAL_DATE__C\
,"VP_Partnerships__c" as VP_PARTNERSHIPS__C\
,"Tech_CountStarterEditionLines__c" as TECH_COUNTSTARTEREDITIONLINES__C\
,"Opportunity_Managment_Forecast_Category__c" as OPPORTUNITY_MANAGMENT_FORECAST_CATEGORY__C\
,"ARR_Test__c" as ARR_TEST__C\
,"Tech_Contains_Online_Business__c" as TECH_CONTAINS_ONLINE_BUSINESS__C\
,"Tech_Contains_Online_Discover__c" as TECH_CONTAINS_ONLINE_DISCOVER__C\
,"Tech_OD_Display_Net_Price__c" as TECH_OD_DISPLAY_NET_PRICE__C\
,"Tech_OD_Display_Discount__c" as TECH_OD_DISPLAY_DISCOUNT__C\
,"DD_Rejection_Date__c" as DD_REJECTION_DATE__C\
,"Dataiku_Entity_requires_approval__c" as DATAIKU_ENTITY_REQUIRES_APPROVAL__C\
,"Tech_Total_Service_Discount__c" as TECH_TOTAL_SERVICE_DISCOUNT__C\
,"ApprovalStatus__c" as APPROVALSTATUS__C\
,"ApprovalsArchived__c" as APPROVALSARCHIVED__C\
,"Initial_Service_Package_Exception__c" as INITIAL_SERVICE_PACKAGE_EXCEPTION__C\
,"CPQ_Subscription_Term_Approval_Level__c" as CPQ_SUBSCRIPTION_TERM_APPROVAL_LEVEL__C\
,"Has_Legacy_Products__c" as HAS_LEGACY_PRODUCTS__C\
,"AA_Level_1_Approver__c" as AA_LEVEL_1_APPROVER__C\
,"AA_Level_2_Approver__c" as AA_LEVEL_2_APPROVER__C\
,"AA_Level_3_Approver__c" as AA_LEVEL_3_APPROVER__C\
,"AA_Partner_Level_Approver__c" as AA_PARTNER_LEVEL_APPROVER__C\
,"CPQ_Product_Approval_Level__c" as CPQ_PRODUCT_APPROVAL_LEVEL__C\
,"AE_Quote_Name__c" as AE_QUOTE_NAME__C\
,"Amended_Contract_End_Date__c" as AMENDED_CONTRACT_END_DATE__C\
,"Amended_Contract_Start_Date__c" as AMENDED_CONTRACT_START_DATE__C\
,"Amended_Contract__c" as AMENDED_CONTRACT__C\
,"Customer_Contact_Email__c" as CUSTOMER_CONTACT_EMAIL__C\
,"Ready_to_Submit__c" as READY_TO_SUBMIT__C\
,"Renewed_Contract_End_Date__c" as RENEWED_CONTRACT_END_DATE__C\
,"Renewed_Contract_Start_Date__c" as RENEWED_CONTRACT_START_DATE__C\
,"Renewed_Contract__c" as RENEWED_CONTRACT__C\
,"Tenant_ID__c" as TENANT_ID__C\
,"Total_Service_List_Amount__c" as TOTAL_SERVICE_LIST_AMOUNT__C\
,"Total_Service_Net_Amount__c" as TOTAL_SERVICE_NET_AMOUNT__C\
,"Marketplace_rollup__c" as MARKETPLACE_ROLLUP__C\
,"Service_Attach_Rate__c" as SERVICE_ATTACH_RATE__C\
,"Total_Service_Discount_Amount__c" as TOTAL_SERVICE_DISCOUNT_AMOUNT__C\
,"Total_Service_Discount__c" as TOTAL_SERVICE_DISCOUNT__C\
,"CPQ_Discount_approval_level__c" as CPQ_DISCOUNT_APPROVAL_LEVEL__C\
,"CPQ_Marketing_Approval_Level__c" as CPQ_MARKETING_APPROVAL_LEVEL__C\
,"CPQ_Payment_terms_Approval_Level__c" as CPQ_PAYMENT_TERMS_APPROVAL_LEVEL__C\
,"CPQ_Renewal_Clause_Approval_Level__c" as CPQ_RENEWAL_CLAUSE_APPROVAL_LEVEL__C\
,"ARR_Converted_USD__c" as ARR_CONVERTED_USD__C\
,"NNARR_Converted_in_USD__c" as NNARR_CONVERTED_IN_USD__C\
,"TCV_Converted_in_USD__c" as TCV_CONVERTED_IN_USD__C\
,"Ironclad_Workflow__c" as IRONCLAD_WORKFLOW__C\
,"Full_Quote_ID__c" as FULL_QUOTE_ID__C\
,"Top_Approver__c" as TOP_APPROVER__C\
,"Prior_Renewal_Upsell__c" as PRIOR_RENEWAL_UPSELL__C\
,"Prior_Initial_Renewal__c" as PRIOR_INITIAL_RENEWAL__C\
,"TECH_Amended_Opportunity_Effective_Date__c" as TECH_AMENDED_OPPORTUNITY_EFFECTIVE_DATE__C\
,"Tech_Contains_Cloud_Dedicated__c" as TECH_CONTAINS_CLOUD_DEDICATED__C\
,"Tech_CountDedicatedEditionLines__c" as TECH_COUNTDEDICATEDEDITIONLINES__C\
,"Tech_NoPORequested__c" as TECH_NOPOREQUESTED__C\
,"Ironclad_Service_Products_on_Quote__c" as IRONCLAD_SERVICE_PRODUCTS_ON_QUOTE__C\
,"Tech_Display_Cloud_Support_Policy__c" as TECH_DISPLAY_CLOUD_SUPPORT_POLICY__C\
,"Has_Controlled_Service_Product_Set_2__c" as HAS_CONTROLLED_SERVICE_PRODUCT_SET_2__C\
,"Has_Controlled_Service_Product__c" as HAS_CONTROLLED_SERVICE_PRODUCT__C\
,"AA_Level_1_Services_Approver__c" as AA_LEVEL_1_SERVICES_APPROVER__C\
,"Tech_Display_Cloud_Dedic_Support_Policy__c" as TECH_DISPLAY_CLOUD_DEDIC_SUPPORT_POLICY__C\
,"Tech_Display_Cloud_SLA__c" as TECH_DISPLAY_CLOUD_SLA__C\
,"Tech_Services_Quote__c" as TECH_SERVICES_QUOTE__C\
,"Requires_EUC_Language__c" as REQUIRES_EUC_LANGUAGE__C\
,"License_File_Shipping_Location__c" as LICENSE_FILE_SHIPPING_LOCATION__C\
,"Tech_DD_Comments_from_OPp__c" as TECH_DD_COMMENTS_FROM_OPP__C\
,"Usage_Data_Collection__c" as USAGE_DATA_COLLECTION__C\
,"META_UNIQUE_HASH" as META_UNIQUE_HASH\
,"META_ROW_HASH" as META_ROW_HASH\
,"META_IS_DELETED" as META_IS_DELETED\
,"META_INSERT_TIMESTAMP" as META_INSERT_TIMESTAMP\
,"META_UPDATE_TIMESTAMP" as META_UPDATE_TIMESTAMP\
\
FROM RAW.SALESFORCE_DSS.QUOTE}