{\rtf1\ansi\ansicpg1252\cocoartf2822
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 ArialMT;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\paperw11900\paperh16840\margl1440\margr1440\vieww28300\viewh16080\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs26\fsmilli13333 \cf0 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 CREATE OR REPLACE DYNAMIC TABLE \{\{CONF\}\}.SALESFORCE_V2.CONTACT\
TARGET_LAG = DOWNSTREAM\
WAREHOUSE = SF_TRANSFORM_WH\
REFRESH_MODE = INCREMENTAL\
INITIALIZE = ON_SCHEDULE\
DATA_METRIC_SCHEDULE = TRIGGER_ON_CHANGES\
as\
SELECT\
--"attributes.type" AS "ATTRIBUTES.TYPE",\
--"attributes.url" AS "ATTRIBUTES.URL",\
"Id" AS "ID",\
case when UPPER("IsDeleted") = 'FALSE' THEN FALSE ELSE TRUE END AS "ISDELETED",\
"MasterRecordId" AS "MASTERRECORDID",\
"AccountId" AS "ACCOUNTID",\
"LastName" AS "LASTNAME",\
"FirstName" AS "FIRSTNAME",\
"Salutation" AS "SALUTATION",\
"Name" AS "NAME",\
"RecordTypeId" AS "RECORDTYPEID",\
"OtherStreet" AS "OTHERSTREET",\
"OtherCity" AS "OTHERCITY",\
"OtherState" AS "OTHERSTATE",\
"OtherPostalCode" AS "OTHERPOSTALCODE",\
"OtherCountry" AS "OTHERCOUNTRY",\
"OtherStateCode" AS "OTHERSTATECODE",\
"OtherCountryCode" AS "OTHERCOUNTRYCODE",\
"OtherLatitude" AS "OTHERLATITUDE",\
"OtherLongitude" AS "OTHERLONGITUDE",\
"OtherGeocodeAccuracy" AS "OTHERGEOCODEACCURACY",\
"OtherAddress" AS "OTHERADDRESS",\
"MailingStreet" AS "MAILINGSTREET",\
"MailingCity" AS "MAILINGCITY",\
"MailingState" AS "MAILINGSTATE",\
"MailingPostalCode" AS "MAILINGPOSTALCODE",\
"MailingCountry" AS "MAILINGCOUNTRY",\
"MailingStateCode" AS "MAILINGSTATECODE",\
"MailingCountryCode" AS "MAILINGCOUNTRYCODE",\
"MailingLatitude" AS "MAILINGLATITUDE",\
"MailingLongitude" AS "MAILINGLONGITUDE",\
"MailingGeocodeAccuracy" AS "MAILINGGEOCODEACCURACY",\
"MailingAddress.city" AS "MAILINGADDRESS_CITY",\
"MailingAddress.country" AS "MAILINGADDRESS_COUNTRY",\
"MailingAddress.countryCode" AS "MAILINGADDRESS_COUNTRYCODE",\
"MailingAddress.geocodeAccuracy" AS "MAILINGADDRESS_GEOCODEACCURACY",\
"MailingAddress.latitude" AS "MAILINGADDRESS_LATITUDE",\
"MailingAddress.longitude" AS "MAILINGADDRESS_LONGITUDE",\
"MailingAddress.postalCode" AS "MAILINGADDRESS_POSTALCODE",\
"MailingAddress.state" AS "MAILINGADDRESS_STATE",\
"MailingAddress.stateCode" AS "MAILINGADDRESS_STATECODE",\
"MailingAddress.street" AS "MAILINGADDRESS_STREET",\
"Phone" AS "PHONE",\
"Fax" AS "FAX",\
"MobilePhone" AS "MOBILEPHONE",\
"HomePhone" AS "HOMEPHONE",\
"OtherPhone" AS "OTHERPHONE",\
"AssistantPhone" AS "ASSISTANTPHONE",\
"ReportsToId" AS "REPORTSTOID",\
"Email" AS "EMAIL",\
"Title" AS "TITLE",\
"Department" AS "DEPARTMENT",\
"AssistantName" AS "ASSISTANTNAME",\
"LeadSource" AS "LEADSOURCE",\
"Birthdate" AS "BIRTHDATE",\
"Description" AS "DESCRIPTION",\
"CurrencyIsoCode" AS "CURRENCYISOCODE",\
"OwnerId" AS "OWNERID",\
"CanAllowPortalSelfReg" AS "CANALLOWPORTALSELFREG",\
"CreatedDate" AS "CREATEDDATE",\
"CreatedById" AS "CREATEDBYID",\
"LastModifiedDate" AS "LASTMODIFIEDDATE",\
"LastModifiedById" AS "LASTMODIFIEDBYID",\
"SystemModstamp" AS "SYSTEMMODSTAMP",\
"LastActivityDate" AS "LASTACTIVITYDATE",\
"LastCURequestDate" AS "LASTCUREQUESTDATE",\
"LastCUUpdateDate" AS "LASTCUUPDATEDATE",\
"LastViewedDate" AS "LASTVIEWEDDATE",\
"LastReferencedDate" AS "LASTREFERENCEDDATE",\
"EmailBouncedReason" AS "EMAILBOUNCEDREASON",\
"EmailBouncedDate" AS "EMAILBOUNCEDDATE",\
"IsEmailBounced" AS "ISEMAILBOUNCED",\
"PhotoUrl" AS "PHOTOURL",\
"Jigsaw" AS "JIGSAW",\
"JigsawContactId" AS "JIGSAWCONTACTID",\
"External_Id__c" AS "EXTERNAL_ID__C",\
"Second_email__c" AS "SECOND_EMAIL__C",\
"Level__c" AS "LEVEL__C",\
"SDR_Status__c" AS "SDR_STATUS__C",\
"First_Action__c" AS "FIRST_ACTION__C",\
"LID__LinkedIn_Company_Id__c" AS "LID__LINKEDIN_COMPANY_ID__C",\
"LID__LinkedIn_Member_Token__c" AS "LID__LINKEDIN_MEMBER_TOKEN__C",\
"Contact_Qualification__c" AS "CONTACT_QUALIFICATION__C",\
"Role__c" AS "ROLE__C",\
"Country__c" AS "COUNTRY__C",\
"HubSpot_Lifecycle_Stage__c" AS "HUBSPOT_LIFECYCLE_STAGE__C",\
"Became_a_MQL_Date__c" AS "BECAME_A_MQL_DATE__C",\
"Contact_Preferred_Language__c" AS "CONTACT_PREFERRED_LANGUAGE__C",\
"Contact_Status__c" AS "CONTACT_STATUS__C",\
"Date_Contact_Became_Open__c" AS "DATE_CONTACT_BECAME_OPEN__C",\
"Date_Contact_Moved_to_In_Process__c" AS "DATE_CONTACT_MOVED_TO_IN_PROCESS__C",\
"Date_Became_Qualified__c" AS "DATE_BECAME_QUALIFIED__C",\
"Account_Type__c" AS "ACCOUNT_TYPE__C",\
"Refuse_Contact__c" AS "REFUSE_CONTACT__C",\
"Date_Moved_to_Dormant__c" AS "DATE_MOVED_TO_DORMANT__C",\
"Region__c" AS "REGION__C",\
"Sub_Region__c" AS "SUB_REGION__C",\
"AI_Maturity_Survey_Results__c" AS "AI_MATURITY_SURVEY_RESULTS__C",\
"Partner_Community_Member__c" AS "PARTNER_COMMUNITY_MEMBER__C",\
"Current_Sequence_Name_URL__c" AS "CURRENT_SEQUENCE_NAME_URL__C",\
"vy_report__Vidyard_Count__c" AS "VY_REPORT__VIDYARD_COUNT__C",\
"Lead_Provider__c" AS "LEAD_PROVIDER__C",\
"Reference_Call_Participations__c" AS "REFERENCE_CALL_PARTICIPATIONS__C",\
"Date_of_Last_Reference_Call__c" AS "DATE_OF_LAST_REFERENCE_CALL__C",\
"account6QA6sense__c" AS "ACCOUNT6QA6SENSE__C",\
"account6QAAgeInDays6sense__c" AS "ACCOUNT6QAAGEINDAYS6SENSE__C",\
"account6QAEndDate6sense__c" AS "ACCOUNT6QAENDDATE6SENSE__C",\
"account6QAStartDate6sense__c" AS "ACCOUNT6QASTARTDATE6SENSE__C",\
"accountBuyingStage6sense__c" AS "ACCOUNTBUYINGSTAGE6SENSE__C",\
"accountIntentScore6sense__c" AS "ACCOUNTINTENTSCORE6SENSE__C",\
"accountNumericalReachScore6sense__c" AS "ACCOUNTNUMERICALREACHSCORE6SENSE__C",\
"accountProfileFit6sense__c" AS "ACCOUNTPROFILEFIT6SENSE__C",\
"accountProfileScore6sense__c" AS "ACCOUNTPROFILESCORE6SENSE__C",\
"contactGrade6sense__c" AS "CONTACTGRADE6SENSE__C",\
"contactIntentScore6sense__c" AS "CONTACTINTENTSCORE6SENSE__C",\
"contactProfileFit6sense__c" AS "CONTACTPROFILEFIT6SENSE__C",\
"contactProfileScore6sense__c" AS "CONTACTPROFILESCORE6SENSE__C",\
"contactUpdateDate6sense__c" AS "CONTACTUPDATEDATE6SENSE__C",\
"Outreach_Tags__c" AS "OUTREACH_TAGS__C",\
"Most_Recent_BDR_Connection_Approval_Date__c" AS "MOST_RECENT_BDR_CONNECTION_APPROVAL_DATE__C",\
"Most_Recent_BDR_Connection_Date__c" AS "MOST_RECENT_BDR_CONNECTION_DATE__C",\
"Contact_Page_Referrer__c" AS "CONTACT_PAGE_REFERRER__C",\
"Is_User_Advocate__c" AS "IS_USER_ADVOCATE__C",\
"Partner_Opportunity_Comarketing_Info__c" AS "PARTNER_OPPORTUNITY_COMARKETING_INFO__C",\
"Partner_Opportunity_Comarketing_Type__c" AS "PARTNER_OPPORTUNITY_COMARKETING_TYPE__C",\
"Partner_Opportunity_Comarketing__c" AS "PARTNER_OPPORTUNITY_COMARKETING__C",\
"Target_Account__c" AS "TARGET_ACCOUNT__C",\
"In_Target_Account_Group__c" AS "IN_TARGET_ACCOUNT_GROUP__C",\
"In_Target_Account_Group_in_Country__c" AS "IN_TARGET_ACCOUNT_GROUP_IN_COUNTRY__C",\
"SDR_Owner__c" AS "SDR_OWNER__C",\
"First_Conversion__c" AS "FIRST_CONVERSION__C",\
"MQL_Origin__c" AS "MQL_ORIGIN__C",\
"Opinion_of_Dataiku__c" AS "OPINION_OF_DATAIKU__C",\
"Met_or_Not_Met__c" AS "MET_OR_NOT_MET__C",\
"Perceived_Level_of_Influence__c" AS "PERCEIVED_LEVEL_OF_INFLUENCE__C",\
"Qualitative_opinion__c" AS "QUALITATIVE_OPINION__C",\
"Lead_Qualification_Document__c" AS "LEAD_QUALIFICATION_DOCUMENT__C",\
"SAL_Meeting_Date__c" AS "SAL_MEETING_DATE__C",\
"State_or_Territory__c" AS "STATE_OR_TERRITORY__C",\
"Contact_Continent__c" AS "CONTACT_CONTINENT__C",\
"Related_Ironclad_Workflow__c" AS "RELATED_IRONCLAD_WORKFLOW__C",\
"DSS_License_Action__c" AS "DSS_LICENSE_ACTION__C",\
"Contact_Request_Comment__c" AS "CONTACT_REQUEST_COMMENT__C",\
"LID__Languages__c" AS "LID__LANGUAGES__C",\
"LID__Level__c" AS "LID__LEVEL__C",\
"LID__No_longer_at_Company__c" AS "LID__NO_LONGER_AT_COMPANY__C",\
"LID__Session_Id__c" AS "LID__SESSION_ID__C",\
"Account_Tiering__c" AS "ACCOUNT_TIERING__C",\
"Number_of_Employees__c" AS "NUMBER_OF_EMPLOYEES__C",\
"LinkedIn_URL__c" AS "LINKEDIN_URL__C",\
"Company_Revenue__c" AS "COMPANY_REVENUE__C",\
"Partnerships_Team_Comments__c" AS "PARTNERSHIPS_TEAM_COMMENTS__C",\
"Date_of_Contact_Request__c" AS "DATE_OF_CONTACT_REQUEST__C",\
"Lead_Interest__c" AS "LEAD_INTEREST__C",\
"Contact_Qualification_Document__c" AS "CONTACT_QUALIFICATION_DOCUMENT__C",\
"Account_Contact_Owner_Match__c" AS "ACCOUNT_CONTACT_OWNER_MATCH__C",\
"Contact_Rating_Business_Stakes__c" AS "CONTACT_RATING_BUSINESS_STAKES__C",\
"Contact_Rating_Business_Stakes_Details__c" AS "CONTACT_RATING_BUSINESS_STAKES_DETAILS__C",\
"Contact_Rating_Data_People__c" AS "CONTACT_RATING_DATA_PEOPLE__C",\
"Contact_Rating_Data_People_Comments__c" AS "CONTACT_RATING_DATA_PEOPLE_COMMENTS__C",\
"Contact_Rating_Technology__c" AS "CONTACT_RATING_TECHNOLOGY__C",\
"Contact_Rating_Technology_Details__c" AS "CONTACT_RATING_TECHNOLOGY_DETAILS__C",\
"Discovery_Trainer_Certification__c" AS "DISCOVERY_TRAINER_CERTIFICATION__C",\
"Discovery_Trainer_Certification_Exp__c" AS "DISCOVERY_TRAINER_CERTIFICATION_EXP__C",\
"Adv_Designer_Trainer_Certification__c" AS "ADV_DESIGNER_TRAINER_CERTIFICATION__C",\
"Adv_Designer_Trainer_Certification_Exp__c" AS "ADV_DESIGNER_TRAINER_CERTIFICATION_EXP__C",\
"Sales_Executive_Accreditation__c" AS "SALES_EXECUTIVE_ACCREDITATION__C",\
"Sales_Executive_Accreditation_Exp__c" AS "SALES_EXECUTIVE_ACCREDITATION_EXP__C",\
"Opportunity_Contact_Role__c" AS "OPPORTUNITY_CONTACT_ROLE__C",\
"Account_Contact_Role__c" AS "ACCOUNT_CONTACT_ROLE__C",\
"Marketing_Territory__c" AS "MARKETING_TERRITORY__C",\
"Event_Comments__c" AS "EVENT_COMMENTS__C",\
"Marketing_Territory_Main__c" AS "MARKETING_TERRITORY_MAIN__C",\
"CloudingoAgent__CES__c" AS "CLOUDINGOAGENT__CES__C",\
"CloudingoAgent__MAR__c" AS "CLOUDINGOAGENT__MAR__C",\
"CloudingoAgent__MAS__c" AS "CLOUDINGOAGENT__MAS__C",\
"CloudingoAgent__MAV__c" AS "CLOUDINGOAGENT__MAV__C",\
"CloudingoAgent__MRDI__c" AS "CLOUDINGOAGENT__MRDI__C",\
"CloudingoAgent__MTZ__c" AS "CLOUDINGOAGENT__MTZ__C",\
"Unsubscribed__c" AS "UNSUBSCRIBED__C",\
"SQA_Date__c" AS "SQA_DATE__C",\
"cbit__ClearbitReady__c" AS "CBIT__CLEARBITREADY__C",\
"cbit__Clearbit__c" AS "CBIT__CLEARBIT__C",\
"cbit__CreatedByClearbit__c" AS "CBIT__CREATEDBYCLEARBIT__C",\
"cbit__Facebook__c" AS "CBIT__FACEBOOK__C",\
"cbit__LinkedIn__c" AS "CBIT__LINKEDIN__C",\
"cbit__Twitter__c" AS "CBIT__TWITTER__C",\
"CloudingoAgent__OAR__c" AS "CLOUDINGOAGENT__OAR__C",\
"CloudingoAgent__OAS__c" AS "CLOUDINGOAGENT__OAS__C",\
"CloudingoAgent__OAV__c" AS "CLOUDINGOAGENT__OAV__C",\
"CloudingoAgent__ORDI__c" AS "CLOUDINGOAGENT__ORDI__C",\
"CloudingoAgent__OTZ__c" AS "CLOUDINGOAGENT__OTZ__C",\
"Marketing_Lead_Sources__c" AS "MARKETING_LEAD_SOURCES__C",\
"Sales_Territory__c" AS "SALES_TERRITORY__C",\
"NPS_Score__c" AS "NPS_SCORE__C",\
"NPS_Submission_Date__c" AS "NPS_SUBMISSION_DATE__C",\
"NPS_Feedbacks__c" AS "NPS_FEEDBACKS__C",\
"NPS_Info__c" AS "NPS_INFO__C",\
"Contact_Role__c" AS "CONTACT_ROLE__C",\
"Time_Spent_on_DSS_c__c" AS "TIME_SPENT_ON_DSS_C__C",\
"Active_in_the_past_15_days__c" AS "ACTIVE_IN_THE_PAST_15_DAYS__C",\
"First_Connection_On_DSS__c" AS "FIRST_CONNECTION_ON_DSS__C",\
"Last_Connection_On_DSS__c" AS "LAST_CONNECTION_ON_DSS__C",\
"Inactive_At__c" AS "INACTIVE_AT__C",\
"First_Name_Format__c" AS "FIRST_NAME_FORMAT__C",\
"Last_Name_Format__c" AS "LAST_NAME_FORMAT__C",\
"Company_Name_Format__c" AS "COMPANY_NAME_FORMAT__C",\
"Secondary_Email__c" AS "SECONDARY_EMAIL__C",\
"Email_Provider__c" AS "EMAIL_PROVIDER__C",\
"adroll__ClickConversion__c" AS "ADROLL__CLICKCONVERSION__C",\
"adroll__ClickCosts__c" AS "ADROLL__CLICKCOSTS__C",\
"adroll__Click_Conversion__c" AS "ADROLL__CLICK_CONVERSION__C",\
"adroll__Clicks__c" AS "ADROLL__CLICKS__C",\
"adroll__ImpressionCosts__c" AS "ADROLL__IMPRESSIONCOSTS__C",\
"adroll__Impressions_External_ID__c" AS "ADROLL__IMPRESSIONS_EXTERNAL_ID__C",\
"adroll__Impressions__c" AS "ADROLL__IMPRESSIONS__C",\
"adroll__LastAdRollTrackingDate__c" AS "ADROLL__LASTADROLLTRACKINGDATE__C",\
"adroll__ViewConversion__c" AS "ADROLL__VIEWCONVERSION__C",\
"adroll__View_Conversion__c" AS "ADROLL__VIEW_CONVERSION__C",\
"Name_of__c" AS "NAME_OF__C",\
"Outreach_Sequence_at_Conversion__c" AS "OUTREACH_SEQUENCE_AT_CONVERSION__C",\
"Cloud_Active__c" AS "CLOUD_ACTIVE__C",\
"Persona__c" AS "PERSONA__C",\
"L1_Certification__c" AS "L1_CERTIFICATION__C",\
"Cloudingo_merge_IDs__c" AS "CLOUDINGO_MERGE_IDS__C",\
"Receive_Community_News__c" AS "RECEIVE_COMMUNITY_NEWS__C",\
"Current_Sequence_Step_Actor_Role__c" AS "CURRENT_SEQUENCE_STEP_ACTOR_ROLE__C",\
"Current_Sequence_Step_Actor__c" AS "CURRENT_SEQUENCE_STEP_ACTOR__C",\
"Current_Sequence_Step_Due__c" AS "CURRENT_SEQUENCE_STEP_DUE__C",\
"Initial_Sequence_Date__c" AS "INITIAL_SEQUENCE_DATE__C",\
"Outreach_Actively_Being_Sequenced__c" AS "OUTREACH_ACTIVELY_BEING_SEQUENCED__C",\
"Outreach_Current_Sequence_ID__c" AS "OUTREACH_CURRENT_SEQUENCE_ID__C",\
"Outreach_Current_Sequence_Name__c" AS "OUTREACH_CURRENT_SEQUENCE_NAME__C",\
"Outreach_Current_Sequence_Status__c" AS "OUTREACH_CURRENT_SEQUENCE_STATUS__C",\
"Outreach_Current_Sequence_Step_Number__c" AS "OUTREACH_CURRENT_SEQUENCE_STEP_NUMBER__C",\
"Outreach_Current_Sequence_Step_Type__c" AS "OUTREACH_CURRENT_SEQUENCE_STEP_TYPE__C",\
"Outreach_Current_Sequence_Task_Due_Date__c" AS "OUTREACH_CURRENT_SEQUENCE_TASK_DUE_DATE__C",\
"Outreach_Current_Sequence_User_SFDC_ID__c" AS "OUTREACH_CURRENT_SEQUENCE_USER_SFDC_ID__C",\
"Outreach_Initial_Sequence_ID__c" AS "OUTREACH_INITIAL_SEQUENCE_ID__C",\
"Outreach_Initial_Sequence_Name__c" AS "OUTREACH_INITIAL_SEQUENCE_NAME__C",\
"Recent_Conversion__c" AS "RECENT_CONVERSION__C",\
"DOZISF__ZoomInfo_Company_ID__c" AS "DOZISF__ZOOMINFO_COMPANY_ID__C",\
"DOZISF__ZoomInfo_First_Updated__c" AS "DOZISF__ZOOMINFO_FIRST_UPDATED__C",\
"DOZISF__ZoomInfo_Id__c" AS "DOZISF__ZOOMINFO_ID__C",\
"Academy_Member__c" AS "ACADEMY_MEMBER__C",\
"Core_Designer_Certification__c" AS "CORE_DESIGNER_CERTIFICATION__C",\
"Core_Designer_Certification_Expiration__c" AS "CORE_DESIGNER_CERTIFICATION_EXPIRATION__C",\
"ML_Practitioner_Certification__c" AS "ML_PRACTITIONER_CERTIFICATION__C",\
"ML_Practitioner_Certification_Expiration__c" AS "ML_PRACTITIONER_CERTIFICATION_EXPIRATION__C",\
"Advanced_Designer_Certification__c" AS "ADVANCED_DESIGNER_CERTIFICATION__C",\
"Advanced_Designer_Certification_Expire__c" AS "ADVANCED_DESIGNER_CERTIFICATION_EXPIRE__C",\
"Developer_Certification__c" AS "DEVELOPER_CERTIFICATION__C",\
"Developer_Certification_Expiration__c" AS "DEVELOPER_CERTIFICATION_EXPIRATION__C",\
"Power_User_Certification__c" AS "POWER_USER_CERTIFICATION__C",\
"Power_User_Certification_Expiration__c" AS "POWER_USER_CERTIFICATION_EXPIRATION__C",\
"Plugin_Creator_Certification__c" AS "PLUGIN_CREATOR_CERTIFICATION__C",\
"Plugin_Creator_Certification_Expiration__c" AS "PLUGIN_CREATOR_CERTIFICATION_EXPIRATION__C",\
"Administrator_Certification__c" AS "ADMINISTRATOR_CERTIFICATION__C",\
"Administrator_Certification_Expiration__c" AS "ADMINISTRATOR_CERTIFICATION_EXPIRATION__C",\
"Solution_Architect_Certification__c" AS "SOLUTION_ARCHITECT_CERTIFICATION__C",\
"Solution_Architect_Certification_Expire__c" AS "SOLUTION_ARCHITECT_CERTIFICATION_EXPIRE__C",\
"Community_Member__c" AS "COMMUNITY_MEMBER__C",\
"Community_Profile__c" AS "COMMUNITY_PROFILE__C",\
"DOZISF__ZoomInfo_Last_Updated__c" AS "DOZISF__ZOOMINFO_LAST_UPDATED__C",\
"Exclude_from_Communications__c" AS "EXCLUDE_FROM_COMMUNICATIONS__C",\
"Activity_Level__c" AS "ACTIVITY_LEVEL__C",\
"Community_Last_Login_Date__c" AS "COMMUNITY_LAST_LOGIN_DATE__C",\
"Academy_Last_Login_Date__c" AS "ACADEMY_LAST_LOGIN_DATE__C",\
"L1_Certification_Expiration__c" AS "L1_CERTIFICATION_EXPIRATION__C",\
"L2_Certification_Expiration__c" AS "L2_CERTIFICATION_EXPIRATION__C",\
"Partner_Lead_Submission_Date__c" AS "PARTNER_LEAD_SUBMISSION_DATE__C",\
"Discovery_Call_Date__c" AS "DISCOVERY_CALL_DATE__C",\
"Outreach_Last_Touched_Date__c" AS "OUTREACH_LAST_TOUCHED_DATE__C",\
"Do_not_contact__c" as "DO_NOT_CONTACT__C",\
"HasOptedOutOfEmail" as "HASOPTEDOUTOFEMAIL",\
"Outreach_Last_Engaged_Date__c" AS "OUTREACH_LAST_ENGAGED_DATE__C",\
"Date_Lead_Moved_to_Discovery_Call_Status__c" AS "DATE_LEAD_MOVED_TO_DISCOVERY_CALL_STATUS__C",\
"Recent_Conversion_Date__c" AS "RECENT_CONVERSION_DATE__C",\
"Date_Discovery_Call_Scheduled__c" AS "DATE_DISCOVERY_CALL_SCHEDULED__C",\
"delpha__DDQ_EmailCompleteness__c" AS "DELPHA__DDQ_EMAILCOMPLETENESS__C",\
"Contact_Do_Not_Compare__c" AS "CONTACT_DO_NOT_COMPARE__C",\
"Contact_Golden__c" AS "CONTACT_GOLDEN__C",\
"tt_itda_watch__Tech_Target_Import_Timestamp__c" AS "TT_ITDA_WATCH__TECH_TARGET_IMPORT_TIMESTAMP__C",\
"MailingAddress" AS "MAILINGADDRESS",\
META_UNIQUE_HASH AS META_UNIQUE_HASH,\
META_ROW_HASH AS META_ROW_HASH,\
META_IS_DELETED AS META_IS_DELETED,\
META_INSERT_TIMESTAMP AS META_INSERT_TIMESTAMP,\
META_UPDATE_TIMESTAMP AS META_UPDATE_TIMESTAMP,\
'SALESFORCE' AS META_SOURCE_NAME\
FROM RAW.SALESFORCE_DSS.CONTACT}