{\rtf1\ansi\ansicpg1252\cocoartf2822
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 ArialMT;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs26\fsmilli13333 \cf0 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 CREATE OR REPLACE DYNAMIC TABLE \{\{CONF\}\}.CLARI_V2.DECLARATIVE_HISTORY\
TARGET_LAG = DOWNSTREAM\
WAREHOUSE = SF_TRANSFORM_WH\
REFRESH_MODE = INCREMENTAL\
INITIALIZE = ON_SCHEDULE\
DATA_METRIC_SCHEDULE = TRIGGER_ON_CHANGES\
as\
WITH\
DECLARATIVE_HISTORY AS (\
-- we have 874,564 records in the DISTINCT raw manual uploaded file\
SELECT DISTINCT\
"userId" AS USER_ID, \
"hierarchyId" AS HIERARCHY_ID, \
"fiscalYear" AS FISCAL_YEAR, \
"fiscalQtr" AS FISCAL_QUARTER, \
"forecastId" AS FORECAST_ID, \
"fieldId" AS FIELD_ID_ORIGINAL, \
TO_TIMESTAMP_TZ("updatedAt") AS UPDATED_AT,\
"updateUserId" AS UPDATED_BY, \
"overrideAction" AS OVERRIDE_ACTION, \
"value" AS VALUE, \
"comment" AS COMMENT, \
"currencyCode" AS CURRENCY_CODE, \
"original_dataset" AS ORIGINAL_DATASET\
FROM RAW.CLARI_DSS.DECLARATIVE_HISTORY DH\
WHERE \
"value" IS NOT NULL \
AND "updatedAt" IS NOT NULL\
)\
\
-- SELECT COUNT(1) FROM DECLARATIVE_HISTORY\
\
,USER_LIST_HIST AS (\
SELECT \
"id" AS USER_ID,\
"name" AS NAME\
FROM RAW.CLARI_DSS.USER_LIST_HISTORY ULH\
WHERE \
"id" IS NOT NULL\
AND "name" IS NOT NULL\
)\
\
-- select count(distinct user_id) / count(user_id) from USER_LIST_HIST\
\
,USER_TERRITORY AS (\
SELECT \
FISCAL_YEAR::REAL AS FISCAL_YEAR,\
NAME AS NAME,\
EMPLOYEE_ID AS EMPLOYEE_ID,\
TERRITORY_LEVEL,\
TERRITORY,\
EMAIL AS EMAIL,\
SALESFORCE_ID\
FROM RAW.TERRITORY.USER_TERRITORY_MAPPING_HISTORY \
)\
\
-- select fiscal_year,name,territory_level,territory,count(1) as cnt from user_territory group by all having cnt > 1\
\
,NAMED AS (\
SELECT\
DH.*,\
UT.NAME AS NAME,\
UT.EMAIL AS EMAIL,\
COALESCE(UT.TERRITORY_LEVEL,'UNKNOWN') AS TERRITORY_LEVEL,\
CASE \
WHEN DH.FISCAL_YEAR = 2022 AND UT.TERRITORY = 'AMERICAS' THEN 'AMER'\
ELSE COALESCE(UT.TERRITORY,'UNKNOWN') \
END AS TERRITORY,\
UT.SALESFORCE_ID,\
SPLIT_PART(DH.FIELD_ID_ORIGINAL,'_',-1) AS TIME_PERIOD_RAW,\
CASE \
WHEN TIME_PERIOD_RAW = 'quarter1' THEN 'Q1'\
WHEN TIME_PERIOD_RAW = 'quarter2' THEN 'Q2'\
WHEN TIME_PERIOD_RAW = 'quarter3' THEN 'Q3'\
WHEN TIME_PERIOD_RAW = 'quarter4' THEN 'Q4'\
WHEN DH.FISCAL_QUARTER = 'Q1' AND TIME_PERIOD_RAW = 'month1' THEN 'M1'\
WHEN DH.FISCAL_QUARTER = 'Q1' AND TIME_PERIOD_RAW = 'month2' THEN 'M2'\
WHEN DH.FISCAL_QUARTER = 'Q1' AND TIME_PERIOD_RAW = 'month3' THEN 'M3'\
WHEN DH.FISCAL_QUARTER = 'Q2' AND TIME_PERIOD_RAW = 'month1' THEN 'M4'\
WHEN DH.FISCAL_QUARTER = 'Q2' AND TIME_PERIOD_RAW = 'month2' THEN 'M5'\
WHEN DH.FISCAL_QUARTER = 'Q2' AND TIME_PERIOD_RAW = 'month3' THEN 'M6'\
WHEN DH.FISCAL_QUARTER = 'Q3' AND TIME_PERIOD_RAW = 'month1' THEN 'M7'\
WHEN DH.FISCAL_QUARTER = 'Q3' AND TIME_PERIOD_RAW = 'month2' THEN 'M8'\
WHEN DH.FISCAL_QUARTER = 'Q3' AND TIME_PERIOD_RAW = 'month3' THEN 'M9'\
WHEN DH.FISCAL_QUARTER = 'Q4' AND TIME_PERIOD_RAW = 'month1' THEN 'M10'\
WHEN DH.FISCAL_QUARTER = 'Q4' AND TIME_PERIOD_RAW = 'month2' THEN 'M11'\
WHEN DH.FISCAL_QUARTER = 'Q4' AND TIME_PERIOD_RAW = 'month3' THEN 'M12'\
ELSE NULL\
END AS TIME_PERIOD_ONLY,\
CONCAT(DH.FISCAL_YEAR,'_',DH.FISCAL_QUARTER) AS TIME_PERIOD,\
CONCAT(DH.FISCAL_YEAR,'_',TIME_PERIOD_ONLY) AS TIME_PERIOD_ID,\
REPLACE(DH.FIELD_ID_ORIGINAL,CONCAT('_',TIME_PERIOD_RAW),'') AS FIELD_ID\
FROM DECLARATIVE_HISTORY DH\
JOIN USER_LIST_HIST ULH\
ON DH.USER_ID = ULH.USER_ID \
LEFT JOIN USER_TERRITORY UT\
ON DH.FISCAL_YEAR = UT.FISCAL_YEAR\
AND ULH.NAME = UT.NAME\
)\
-- select count(1) from named -- 890,675\
-- select * from named\
SELECT \
'Booking' AS ARR_VERSION, -- All historical declaratives were for Booking ARR\
N.HIERARCHY_ID,\
N.FISCAL_YEAR,\
N.FISCAL_QUARTER,\
N.TIME_PERIOD,\
N.TIME_PERIOD_ID,\
N.TIME_PERIOD_RAW,\
N.TIME_PERIOD_ONLY,\
N.TERRITORY_LEVEL,\
N.TERRITORY,\
N.FORECAST_ID,\
N.FIELD_ID_ORIGINAL,\
N.FIELD_ID,\
FM.FIELD_NAME_MAPPED,\
CONCAT(N.USER_ID,':',N.HIERARCHY_ID) AS USER_ID,\
N.NAME,\
N.EMAIL,\
N.SALESFORCE_ID,\
N.UPDATED_AT,\
N.UPDATED_BY,\
N.VALUE,\
N.CURRENCY_CODE,\
N.OVERRIDE_ACTION,\
N.COMMENT,\
N.ORIGINAL_DATASET\
FROM NAMED N\
JOIN RAW.CLARI.FIELDS_MAPPING FM\
ON N.FORECAST_ID = FM.FORECAST_ID\
AND N.FIELD_ID = FM.FIELD_ID\
AND FM.FIELD_NAME_MAPPED NOT LIKE '%Duplicate%'}