{\rtf1\ansi\ansicpg1252\cocoartf2822
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 ArialMT;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs26\fsmilli13333 \cf0 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 CREATE OR REPLACE DYNAMIC TABLE \{\{CONF\}\}.CLARI_V2.USER\
TARGET_LAG = DOWNSTREAM\
WAREHOUSE = SF_TRANSFORM_WH\
REFRESH_MODE = INCREMENTAL\
INITIALIZE = ON_SCHEDULE\
DATA_METRIC_SCHEDULE = TRIGGER_ON_CHANGES\
as\
WITH\
USERS AS (\
SELECT DISTINCT\
"userId" AS USER_ID,\
"name" AS NAME,\
"email" AS EMAIL,\
"hierarchyName" AS HIERARCHY_NAME,\
META_IS_DELETED\
FROM RAW.CLARI_DSS.DECLARATIVE\
\
)\
,ACTIVE_USERS AS (\
SELECT \
USER_ID,\
NAME,\
EMAIL,\
HIERARCHY_NAME\
FROM USERS\
WHERE META_IS_DELETED = FALSE\
)\
\
SELECT \
USER_ID,\
NAME,\
EMAIL,\
HIERARCHY_NAME,\
TRUE AS META_ACTIVE_FLAG\
FROM ACTIVE_USERS\
UNION\
SELECT \
USER_ID,\
NAME,\
EMAIL,\
HIERARCHY_NAME,\
FALSE AS META_ACTIVE_FLAG\
FROM USERS U\
WHERE NOT EXISTS (\
SELECT 1 \
FROM ACTIVE_USERS AU\
WHERE AU.USER_ID = U.USER_ID\
)}